### ISSUE TITLE
Error filtering template: Invalid block type: pl-s

### ISSUE THREAD

**Issue by giacomoleopardi** [karliuka/m2.ProductMostOrdered#1]
Hi,

I Have create new page bestseller CMS with this content:

`{{block class='Faonni\ProductMostOrdered\Block\ProductList' 
		template='Faonni_ProductMostOrdered::product/list/items.phtml' 
		title='Most Ordered Products'
		period='monthly'
		interval='3'
		num_products='6'
}}`

In my site: (www.mymagento2.com/bestseller) I have this error:

`[2017-12-04 11:29:57] report.CRITICAL: Invalid block type: pl-s {"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): Invalid block type: pl-s at /var/www/html/vendor/magento/framework/View/Layout/Generator/Block.php:263, ReflectionException(code: -1): Class pl-s does not exist at /var/www/html/vendor/magento/framework/Code/Reader/ClassReader.php:19)"} []`

Can you helm me?
thanks

**Comment by karliuka** [comment]
Hi,
Invalid block type: pl-s { ... This means that the system cannot find a block **pl-s**. This is not a module ProductMostOrdered. Please check your layouts and sms content by keyword **pl-s**.
